name: Build and Run Kotlin Project

on: push
#   schedule:
#     - cron: '0 0 * * *' # 每天 00:00 UTC 执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run application
      run: ./gradlew run
