name: Build and Run Kotlin Project

on: push
#   schedule:
#     - cron: '0 0 * * *' # 每天 00:00 UTC 执行

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: ./github_actions

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./github_actions

    - name: Run
      run: ./gradlew run
      working-directory: ./github_actions

    - name: Commit output
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: update file(s) skip-checks:true


